CREATE VIEW ArtistInterestView AS
SELECT CUSTOMER.LastName AS CustomerLastName, CUSTOMER.FirstName AS CustomerFirstName, ARTIST.LastName AS ArtistName
FROM CUSTOMER LEFT JOIN CUSTOMER_ARTIST_INT
	ON CUSTOMER.CustomerID = CUSTOMER_ARTIST_INT.CustomerID
    	RIGHT JOIN ARTIST
        	ON CUSTOMER_ARTIST_INT.ArtistID = ARTIST.ArtistID